UG-353 — Create Post Activation Journey template
Financial-Times/n-messaging-client pull request #335
Opened 2021-01-22 10:49 UTC by bolajiadeyemi

New message template for **Post Activation Journey** feedback popup.

##Ticket
https://financialtimes.atlassian.net/browse/UG-353

##ScreenShot
![Screenshot 2021-01-22 at 10 38 53](https://user-images.githubusercontent.com/13418091/105480753-0a295080-5c9e-11eb-8922-b19c282247fc.png)

2021-01-25 12:22 UTC, jamesnicholls requested changes
Good work, but there's still some issues to address. Also, could you take a screenshot of the message on top of the homepage and article page and check with Emily if she's happy with the design? Thanks.

2021-01-25 12:22 UTC, jamesnicholls commented on server/templates/partials/bottom/post-activation-journey.html
> +				<a href="https://survey.ft.com/jfe/form/SV_8BLQylXVJFXxXn" class="o-cookie-message__button">Leave Feedback</a>
**issue:** I get an error message when clicking on this link. Can you check the URL with Fraser/Emily?

2021-01-25 12:22 UTC, jamesnicholls commented on server/templates/partials/bottom/post-activation-journey.html
> +				<a href="https://survey.ft.com/jfe/form/SV_8BLQylXVJFXxXn" class="o-cookie-message__button">Leave Feedback</a>
**issue:** I think this element will need a class of `o-banner__link` or a data attribute of `n-messaging-banner-action` in order for the `act` event to fire. The events are stored in Volt and are used to determine whether to show the banner again.

2021-01-25 12:22 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.scss
> +	}
**thought:** I think these overrides won't be needed once you get rid of the `themeSlateLemon` true option from the template.

2021-01-25 14:50 UTC, bolajiadeyemi commented on client/components/bottom/post-activation-journey/main.js
> +module.exports = (banner, done) => {
I added it because of the custom close [button](https://github.com/Financial-Times/n-messaging-client/blob/fb5514e1df03fbbf1b9cb00d89bbc12bb4bff236/server/templates/partials/bottom/post-activation-journey.html#L13)

2021-01-25 14:55 UTC, bolajiadeyemi commented on server/templates/partials/bottom/post-activation-journey.html
> +				<a href="https://survey.ft.com/jfe/form/SV_8BLQylXVJFXxXn" class="o-cookie-message__button">Leave Feedback</a>
Updated with the right URL: https://survey.ft.com/jfe/form/SV_8BLQylXVJFXxXnL

2021-01-26 09:20 UTC, jamesnicholls requested changes
A couple more tweaks, thanks.

2021-01-26 09:20 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.scss
> +		}
**issue:** This selector doesn't target any element, can you remove it please?

2021-01-26 09:20 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.scss
> +	& --close:hover {
```suggestion
	&--close:hover {
```

2021-01-26 09:20 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.scss
> +		display: none;
**suggestion:** If you pass `suppressCloseButton` when calling the `n-messaging-client/server/templates/components/o-banner` partial, the button won't be rendered and you won't have to use CSS to hide it.

2021-01-26 09:20 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.js
> +module.exports = (banner, done) => {
Ah okay, that makes sense.

2021-01-26 09:20 UTC, jamesnicholls commented on server/templates/partials/bottom/post-activation-journey.html
> +				<a href="https://survey.ft.com/jfe/form/SV_8BLQylXVJFXxXnL" class="o-banner__button" data-o-banner-action="Leave Feedback" data-o-banner-action-type="" target="_blank" rel="noopener" n-messaging-
**question:** Why did you add the `data-o-banner-action` and `data-o-banner-action-type` attributes? What do they do? Also I think you need to add `-type` to the end of the `n-messaging-banner-action` attribute (see https://github.com/Financial-Times/n-messaging-client/blob/master/client/bottom-slot.js#L78)

2021-01-26 09:38 UTC, bolajiadeyemi commented on client/components/bottom/post-activation-journey/main.scss
> +		display: none;
Ah, okay. Thanks

2021-01-26 09:51 UTC, jamesnicholls commented on server/templates/partials/bottom/post-activation-journey.html
> +		closeLabel="Close the banner"
```suggestion
```

2021-01-26 09:55 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.scss
> +		margin-left: oSpacingByName("s4");
**issue:** You removed the `flex` rules and now the link and button are side-by-side, instead of aligned to the edges of the message container. Was that deliberate?

2021-01-26 10:06 UTC, jamesnicholls commented on client/components/bottom/post-activation-journey/main.scss
> +		margin-left: oSpacingByName("s4");
Having the button and link side-by-side is the preferred design.

2021-01-26 10:22 UTC, jamesnicholls approved these changes
All good now, thanks for your revisions.

2021-01-26 10:25 UTC, merged