Change onboarding variant name
Financial-Times/n-messaging-client pull request #374
Opened 2021-06-21 12:41 UTC by Shamarni96

Changed variant names from `onboarding` to `activation`

2021-06-22 10:43 UTC, jamesnicholls requested changes
Good work. Everything works well. I have suggested some small improvements to the code. Could you check the design with Tasha/Dilyana?

Also could you delete the `package-lock.json` file? I don't think this repo uses it.

2021-06-25 12:55 UTC, meel-io reviewed
The code looks good and it works perfectly on my local. I left a minor question but it's not a blocker.

2021-06-25 12:55 UTC, meel-io commented on server/templates/partials/bottom/activation-not-complete.html
> +			<div class="o-banner__content o-banner__content--long">
**question**: why do we need `--long` and `--short` versions of the markup? I thought they were used if it was needed to have different versions by screen size but they look like they have the same content.

2021-06-29 09:58 UTC, bolajiadeyemi submitted a review, later dismissed

2021-06-29 10:04 UTC, meel-io submitted a review, later dismissed

2021-06-29 14:40 UTC, jamesnicholls requested changes
The client-side JS is not running because the `.o-banner` element is missing the `data-n-messaging-component`. I recommend that you use the `/server/templates/components/o-banner` template so that all the necessary attributes are in the HTML.

Also, the messages are missing the close button.

2021-06-29 14:40 UTC, jamesnicholls commented on server/templates/partials/bottom/activation-not-complete.html
> +	<div class="o-banner o-banner--small o-banner--product" data-o-component="o-banner">
**suggestion:** You could `n-messaging-client/server/templates/components/o-banner` template to avoid a little bit of duplication here.

2021-06-29 14:40 UTC, jamesnicholls commented on server/templates/partials/bottom/activation-not-complete.html
> +			</div>
**nitpick:** The indentation is a little out-of-line here.

2021-07-01 13:28 UTC, meel-io commented
> The client-side JS is not running because the `.o-banner` element is missing the `data-n-messaging-component`. I recommend that you use the `/server/templates/components/o-banner` template so that all the necessary attributes are in the HTML.
> 
> Also, the messages are missing the close button.

Added the `/server/templates/components/o-banner` template and seems to be working fine 👍

2021-07-02 11:13 UTC, bolajiadeyemi approved these changes

2021-07-02 11:47 UTC, jamesnicholls commented
Tracking events are working now. Good to go!

2021-07-02 13:47 UTC, leannecornish-ft approved these changes

2021-07-02 14:02 UTC, jamesnicholls approved these changes

2021-07-02 14:03 UTC, merged