ACC1241 - Open Day Premium Upsell banner
Financial-Times/n-messaging-client pull request #401
Opened 2021-10-27 16:02 UTC by asugar13

Open Day banner to show on premium articles for standard B2c users. This banner will be shown on Nov 3rd 2021.

<img width="1438" alt="Screenshot 2021-11-01 at 10 12 11" src="https://user-images.githubusercontent.com/10453619/139656217-7146fe2d-b2da-4657-ac95-a95b7e3ee408.png">

2021-11-01 10:14 UTC, asugar13 commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<span class="lower-message">Upgrade your subscription today for unrestricted access to all the FT has to offer across ft.com, the app and newsletters.</span>
managed to change to p tags

2021-11-01 11:36 UTC, jamesnicholls requested changes
There are a couple of issues that I think need to be addressed before being deployed, like the overly broad `a` selector in the Sass file, and the ensuring the tracking events are being sent correctly.

Also I have a question about how displaying the message after the page has rendered affects accessibility.

2021-11-01 11:36 UTC, jamesnicholls commented on client/components/top/open-day-premium-upsell/main.scss
> +a {
**issue:** I think this scope of this selector is too broad. It will affect any link on the page.

2021-11-01 11:36 UTC, jamesnicholls commented on client/components/top/open-day-premium-upsell/main.js
> +		openDayBanner.style.display = 'block';
**question:** Have you tested this in a screen reader (e.g. Mac OS Voiceover)? Do you know if the message will be announced by screen readers if it is displayed after the page has rendered?

2021-11-01 11:36 UTC, jamesnicholls commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<a href="https://www.ft.com/manage/subscription/change/da448d11-851d-545c-dc0e-e9a2aef62e54" id="button" class="o-message__actions__primary">Upgrade to Premium</a>
**suggestion:** Any reason not to use `o-buttons` for the button element?

2021-11-01 11:36 UTC, jamesnicholls commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<a href="https://www.ft.com/manage/subscription/change/da448d11-851d-545c-dc0e-e9a2aef62e54" id="button" class="o-message__actions__primary">Upgrade to Premium</a>
**issue:** I think you might have to give this element a class of `o-message__button` or `o-message_link` or a data attribute with the key `data-o-message-action` in order for the tracking events to work correctly. See https://github.com/Financial-Times/n-messaging-client/blob/72b9c0f8e5124afd1b5ef0308b86e0884ee07851/client/top-slot.js#L67-L94.

2021-11-01 11:43 UTC, asugar13 commented on client/components/top/open-day-premium-upsell/main.scss
> +a {
Understood and changing the selector to a class. I thought the styles would only be affected to the newly created component.

2021-11-01 11:52 UTC, asugar13 commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<a href="https://www.ft.com/manage/subscription/change/da448d11-851d-545c-dc0e-e9a2aef62e54" id="button" class="o-message__actions__primary">Upgrade to Premium</a>
I have followed the origami example in https://www.ft.com/__origami/service/build/v3/demo?component=o-message%405.0.1&demo=notice-custom&system_code=origami-repo-data&brand=master
This was not using an `a` tag instead of `o-buttons` for the button component. However I can confirm that there are tracking events after clicking on the button. I believe it's because it's wrapped in a `div` with class `o-message__actions`

2021-11-02 09:01 UTC, asugar13 commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<a href="https://www.ft.com/manage/subscription/change/da448d11-851d-545c-dc0e-e9a2aef62e54" id="button" class="o-message__actions__primary">Upgrade to Premium</a>
Update: You were right. A generic click event was being generated but the `n-messaging-client` click event was not being generated. After some time on it I realized it wasn't only because of needing to have `data-o-message-action` on the `a` tag but also because I needed `data-n-messaging-component` on the top level div

2021-11-02 09:03 UTC, asugar13 commented on client/components/top/open-day-premium-upsell/main.js
> +		openDayBanner.style.display = 'block';
I have tried this on Mac OS Voiceover and it worked fine (I can demo it to you if you want). I have added `aria-live="polite"` to the top level div just in case (I tried that on the Voiceover app too and it was fine as well)

2021-11-02 10:28 UTC, jamesnicholls commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<a href="https://www.ft.com/manage/subscription/change/da448d11-851d-545c-dc0e-e9a2aef62e54" id="button" class="o-message__actions__primary">Upgrade to Premium</a>
Hmm, I still don't see any `click` events being sent to Spoor.

2021-11-02 11:47 UTC, asugar13 commented on server/templates/partials/top/open-day-premium-upsell.html
> +					<a href="https://www.ft.com/manage/subscription/change/da448d11-851d-545c-dc0e-e9a2aef62e54" id="button" class="o-message__actions__primary">Upgrade to Premium</a>
@jamesnicholls  please see the screen capture below. I have checked with @KirtiSiddapur from analytics

https://user-images.githubusercontent.com/10453619/139840542-701599b4-d30b-4f5d-9027-35fc31fc4847.mov

2021-11-02 12:05 UTC, jamesnicholls submitted a review, later dismissed

2021-11-02 13:00 UTC, binaryberry approved these changes
Looking great! The approach of relying on css tags to detect if an article is premium is fine given we're planning on reverting this in less than 48 hours, it doesn't have to be durable.
Well done for pulling this off, with the tracking to boot!

2021-11-02 14:01 UTC, merged