Make tweaks to academia cta message
Financial-Times/n-messaging-client pull request #465
Opened 2022-06-20 14:17 UTC by Shamarni96

### Description
made design tweaks for the academiaCTA message.

### Ticket
https://financialtimes.atlassian.net/browse/UG-911

2022-06-21 08:58 UTC, ivomurrell approved these changes

2022-06-21 10:35 UTC, jamesnicholls requested changes
The changes to the font sizes need to be applied at desktop (large) screen sizes.

2022-06-21 10:35 UTC, jamesnicholls commented on client/components/bottom/academia-cta/main.scss
> -		font-size: 20px;
It's the desktop (line 30) that needs to change to 24px font size

2022-06-21 10:35 UTC, jamesnicholls commented on client/components/bottom/academia-cta/main.scss
> -		font-size: 18px;
It's the desktop (line 44) that needs to change to 20px

2022-06-23 14:43 UTC, jamesnicholls approved these changes
Looks great, thanks.

2022-06-23 15:15 UTC, jenniferemshepherd approved these changes
Top work 🥳

2022-06-23 15:42 UTC, merged